name: PHP Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: php:7.3-cli-alpine
    steps:
    - uses: actions/checkout@v2

    - name: Install composer
      run: apk add -u curl; sh .github/composer.sh; mv composer.phar /usr/local/bin/composer; chmod +x /usr/local/bin/composer

    - name: Validate composer.json
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run unit tests
      run: vendor/bin/phpunit --testsuite "Unit tests"

    - name: Run code style checks
      run: vendor/bin/phpcs

    - name: Run static analysis
      run: vendor/bin/phpcs